# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 16:38
from __future__ import unicode_literals

import application.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_auto_20170418_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specialty',
            options={'verbose_name': 'specialty', 'verbose_name_plural': 'specialties'},
        ),
        migrations.AlterField(
            model_name='application',
            name='appointment',
            field=models.DateTimeField(error_messages={'unique': 'Sorry, this time slot is not available.'}, validators=[application.validators.validate_past], verbose_name='appointment'),
        ),
        migrations.AlterField(
            model_name='application',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Specialist', unique_for_date='appointment', verbose_name='specialist'),
        ),
    ]
