# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 20:02
from __future__ import unicode_literals

import application.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0009_auto_20170419_0132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='application',
            options={'verbose_name': 'application', 'verbose_name_plural': 'applications'},
        ),
        migrations.AlterModelOptions(
            name='specialist',
            options={'verbose_name': 'specialist', 'verbose_name_plural': 'specialists'},
        ),
        migrations.AddField(
            model_name='application',
            name='specialty',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to='application.Specialty', verbose_name='specialty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='appointment',
            field=models.DateTimeField(validators=[application.validators.validate_past], verbose_name='appointment time'),
        ),
        migrations.AlterField(
            model_name='application',
            name='specialist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Specialist', verbose_name='specialist'),
        ),
        migrations.AlterField(
            model_name='specialist',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.Specialty', verbose_name='specialty'),
        ),
    ]
