# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-18 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0010_auto_20170419_0402'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='specialty',
        ),
    ]
